// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
// prisma.config.ts
import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';

// Carga explícitamente el archivo .env
dotenv.config();

export default defineConfig({
  migrations: {
      seed: 'node prisma/seed.js',
    },
  datasource: {
    // Ahora sí estará disponible para el comando migrate
    url: process.env.DATABASE_URL,
  },
});
